/**
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DocumentAttachment', 'model/FileFromSf', 'model/InlineIntegrationData', 'model/InlinePrefillTags', 'model/SigningLog', 'model/SignRequest', 'model/Team1', 'model/User'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DocumentAttachment'), require('./FileFromSf'), require('./InlineIntegrationData'), require('./InlinePrefillTags'), require('./SigningLog'), require('./SignRequest'), require('./Team1'), require('./User'));
  } else {
    // Browser globals (root is window)
    if (!root.SignrequestClient) {
      root.SignrequestClient = {};
    }
    root.SignrequestClient.Document = factory(root.SignrequestClient.ApiClient, root.SignrequestClient.DocumentAttachment, root.SignrequestClient.FileFromSf, root.SignrequestClient.InlineIntegrationData, root.SignrequestClient.InlinePrefillTags, root.SignrequestClient.SigningLog, root.SignrequestClient.Signrequest, root.SignrequestClient.Team1, root.SignrequestClient.User);
  }
}(this, function(ApiClient, DocumentAttachment, FileFromSf, InlineIntegrationData, InlinePrefillTags, SigningLog, Signrequest, Team1, User) {
  'use strict';




  /**
   * The Document model module.
   * @module model/Document
   * @version v1
   */

  /**
   * Constructs a new <code>Document</code>.
   * @alias module:model/Document
   * @class
   */
  var exports = function() {
    var _this = this;



























  };

  /**
   * Constructs a <code>Document</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Document} obj Optional instance to populate.
   * @return {module:model/Document} The populated <code>Document</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('team')) {
        obj['team'] = Team1.constructFromObject(data['team']);
      }
      if (data.hasOwnProperty('uuid')) {
        obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
      }
      if (data.hasOwnProperty('user')) {
        obj['user'] = User.constructFromObject(data['user']);
      }
      if (data.hasOwnProperty('file_as_pdf')) {
        obj['file_as_pdf'] = ApiClient.convertToType(data['file_as_pdf'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('external_id')) {
        obj['external_id'] = ApiClient.convertToType(data['external_id'], 'String');
      }
      if (data.hasOwnProperty('frontend_id')) {
        obj['frontend_id'] = ApiClient.convertToType(data['frontend_id'], 'String');
      }
      if (data.hasOwnProperty('file')) {
        obj['file'] = ApiClient.convertToType(data['file'], 'String');
      }
      if (data.hasOwnProperty('file_from_url')) {
        obj['file_from_url'] = ApiClient.convertToType(data['file_from_url'], 'String');
      }
      if (data.hasOwnProperty('events_callback_url')) {
        obj['events_callback_url'] = ApiClient.convertToType(data['events_callback_url'], 'String');
      }
      if (data.hasOwnProperty('file_from_content')) {
        obj['file_from_content'] = ApiClient.convertToType(data['file_from_content'], 'String');
      }
      if (data.hasOwnProperty('file_from_content_name')) {
        obj['file_from_content_name'] = ApiClient.convertToType(data['file_from_content_name'], 'String');
      }
      if (data.hasOwnProperty('template')) {
        obj['template'] = ApiClient.convertToType(data['template'], 'String');
      }
      if (data.hasOwnProperty('prefill_tags')) {
        obj['prefill_tags'] = ApiClient.convertToType(data['prefill_tags'], [InlinePrefillTags]);
      }
      if (data.hasOwnProperty('integrations')) {
        obj['integrations'] = ApiClient.convertToType(data['integrations'], [InlineIntegrationData]);
      }
      if (data.hasOwnProperty('file_from_sf')) {
        obj['file_from_sf'] = FileFromSf.constructFromObject(data['file_from_sf']);
      }
      if (data.hasOwnProperty('auto_delete_days')) {
        obj['auto_delete_days'] = ApiClient.convertToType(data['auto_delete_days'], 'Number');
      }
      if (data.hasOwnProperty('pdf')) {
        obj['pdf'] = ApiClient.convertToType(data['pdf'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('signrequest')) {
        obj['signrequest'] = Signrequest.constructFromObject(data['signrequest']);
      }
      if (data.hasOwnProperty('api_used')) {
        obj['api_used'] = ApiClient.convertToType(data['api_used'], 'Boolean');
      }
      if (data.hasOwnProperty('signing_log')) {
        obj['signing_log'] = SigningLog.constructFromObject(data['signing_log']);
      }
      if (data.hasOwnProperty('security_hash')) {
        obj['security_hash'] = ApiClient.convertToType(data['security_hash'], 'String');
      }
      if (data.hasOwnProperty('attachments')) {
        obj['attachments'] = ApiClient.convertToType(data['attachments'], [DocumentAttachment]);
      }
      if (data.hasOwnProperty('auto_delete_after')) {
        obj['auto_delete_after'] = ApiClient.convertToType(data['auto_delete_after'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {module:model/Team1} team
   */
  exports.prototype['team'] = undefined;
  /**
   * @member {String} uuid
   */
  exports.prototype['uuid'] = undefined;
  /**
   * @member {module:model/User} user
   */
  exports.prototype['user'] = undefined;
  /**
   * Temporary URL to original file as PDF, expires in five minutes
   * @member {String} file_as_pdf
   */
  exports.prototype['file_as_pdf'] = undefined;
  /**
   * Defaults to filename, including extension
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * ID used to reference document in external system
   * @member {String} external_id
   */
  exports.prototype['external_id'] = undefined;
  /**
   * Shared secret used in conjunction with <a href=\"#section/Frontend-API/SignRequest-js-client-(beta)\">SignRequest-js client</a> to grant user access to a document that's not a member of the document's team
   * @member {String} frontend_id
   */
  exports.prototype['frontend_id'] = undefined;
  /**
   * Temporary URL to original file, expires in five minutes
   * @member {String} file
   */
  exports.prototype['file'] = undefined;
  /**
   * Publicly accessible URL of document to be downloaded by SignRequest
   * @member {String} file_from_url
   */
  exports.prototype['file_from_url'] = undefined;
  /**
   * URL at which to receive [event callbacks](#section/Events/Events-callback) for this document
   * @member {String} events_callback_url
   */
  exports.prototype['events_callback_url'] = undefined;
  /**
   * Base64 encoded document content
   * @member {String} file_from_content
   */
  exports.prototype['file_from_content'] = undefined;
  /**
   * Filename, including extension. Required when using `file_from_content`.
   * @member {String} file_from_content_name
   */
  exports.prototype['file_from_content_name'] = undefined;
  /**
   * @member {String} template
   */
  exports.prototype['template'] = undefined;
  /**
   * Prefill signer input data, see [prefill tags](#section/Preparing-a-document/Prefill-tags-templates)
   * @member {Array.<module:model/InlinePrefillTags>} prefill_tags
   */
  exports.prototype['prefill_tags'] = undefined;
  /**
   * @member {Array.<module:model/InlineIntegrationData>} integrations
   */
  exports.prototype['integrations'] = undefined;
  /**
   * @member {module:model/FileFromSf} file_from_sf
   */
  exports.prototype['file_from_sf'] = undefined;
  /**
   * Number of days after which a finished document (signed/cancelled/declined) will be automatically deleted
   * @member {Number} auto_delete_days
   */
  exports.prototype['auto_delete_days'] = undefined;
  /**
   * Temporary URL to signed document as PDF, expires in five minutes
   * @member {String} pdf
   */
  exports.prototype['pdf'] = undefined;
  /**
   * `co`: converting, `ne`: new, `se`: sent, `vi`: viewed, `si`: signed, `do`: downloaded, `sd`: signed and downloaded, `ca`: cancelled, `de`: declined, `ec`: error converting, `es`: error sending, `xp`: expired
   * @member {module:model/Document.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {module:model/Signrequest} signrequest
   */
  exports.prototype['signrequest'] = undefined;
  /**
   * Indicates whether document was created using the API
   * @member {Boolean} api_used
   */
  exports.prototype['api_used'] = undefined;
  /**
   * @member {module:model/SigningLog} signing_log
   */
  exports.prototype['signing_log'] = undefined;
  /**
   * SHA256 hash of PDF contents
   * @member {String} security_hash
   */
  exports.prototype['security_hash'] = undefined;
  /**
   * @member {Array.<module:model/DocumentAttachment>} attachments
   */
  exports.prototype['attachments'] = undefined;
  /**
   * Date and time calculated using `auto_delete_days` after which a finished document (signed/cancelled/declined) will be automatically deleted
   * @member {Date} auto_delete_after
   */
  exports.prototype['auto_delete_after'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "co"
     * @const
     */
    "co": "co",
    /**
     * value: "ne"
     * @const
     */
    "ne": "ne",
    /**
     * value: "se"
     * @const
     */
    "se": "se",
    /**
     * value: "vi"
     * @const
     */
    "vi": "vi",
    /**
     * value: "si"
     * @const
     */
    "si": "si",
    /**
     * value: "do"
     * @const
     */
    "do": "do",
    /**
     * value: "sd"
     * @const
     */
    "sd": "sd",
    /**
     * value: "ca"
     * @const
     */
    "ca": "ca",
    /**
     * value: "de"
     * @const
     */
    "de": "de",
    /**
     * value: "ec"
     * @const
     */
    "ec": "ec",
    /**
     * value: "es"
     * @const
     */
    "es": "es",
    /**
     * value: "xp"
     * @const
     */
    "xp": "xp"  };


  return exports;
}));


