/*
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Placeholder'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Placeholder'));
  } else {
    // Browser globals (root is window)
    if (!root.SignrequestClient) {
      root.SignrequestClient = {};
    }
    root.SignrequestClient.DocumentSignerTemplateConf = factory(root.SignrequestClient.ApiClient, root.SignrequestClient.Placeholder);
  }
}(this, function(ApiClient, Placeholder) {
  'use strict';




  /**
   * The DocumentSignerTemplateConf model module.
   * @module model/DocumentSignerTemplateConf
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>DocumentSignerTemplateConf</code>.
   * @alias module:model/DocumentSignerTemplateConf
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>DocumentSignerTemplateConf</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentSignerTemplateConf} obj Optional instance to populate.
   * @return {module:model/DocumentSignerTemplateConf} The populated <code>DocumentSignerTemplateConf</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('signer_index')) {
        obj['signer_index'] = ApiClient.convertToType(data['signer_index'], 'Number');
      }
      if (data.hasOwnProperty('needs_to_sign')) {
        obj['needs_to_sign'] = ApiClient.convertToType(data['needs_to_sign'], 'Boolean');
      }
      if (data.hasOwnProperty('approve_only')) {
        obj['approve_only'] = ApiClient.convertToType(data['approve_only'], 'Boolean');
      }
      if (data.hasOwnProperty('notify_only')) {
        obj['notify_only'] = ApiClient.convertToType(data['notify_only'], 'Boolean');
      }
      if (data.hasOwnProperty('in_person')) {
        obj['in_person'] = ApiClient.convertToType(data['in_person'], 'Boolean');
      }
      if (data.hasOwnProperty('order')) {
        obj['order'] = ApiClient.convertToType(data['order'], 'Number');
      }
      if (data.hasOwnProperty('placeholders')) {
        obj['placeholders'] = ApiClient.convertToType(data['placeholders'], [Placeholder]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} signer_index
   */
  exports.prototype['signer_index'] = undefined;
  /**
   * @member {Boolean} needs_to_sign
   */
  exports.prototype['needs_to_sign'] = undefined;
  /**
   * @member {Boolean} approve_only
   */
  exports.prototype['approve_only'] = undefined;
  /**
   * @member {Boolean} notify_only
   */
  exports.prototype['notify_only'] = undefined;
  /**
   * @member {Boolean} in_person
   */
  exports.prototype['in_person'] = undefined;
  /**
   * @member {Number} order
   */
  exports.prototype['order'] = undefined;
  /**
   * @member {Array.<module:model/Placeholder>} placeholders
   */
  exports.prototype['placeholders'] = undefined;



  return exports;
}));


