/*
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SignrequestClient) {
      root.SignrequestClient = {};
    }
    root.SignrequestClient.DocumentAttachment = factory(root.SignrequestClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DocumentAttachment model module.
   * @module model/DocumentAttachment
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>DocumentAttachment</code>.
   * @alias module:model/DocumentAttachment
   * @class
   * @param document {String} 
   */
  var exports = function(document) {
    var _this = this;








    _this['document'] = document;
  };

  /**
   * Constructs a <code>DocumentAttachment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentAttachment} obj Optional instance to populate.
   * @return {module:model/DocumentAttachment} The populated <code>DocumentAttachment</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('uuid')) {
        obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('file')) {
        obj['file'] = ApiClient.convertToType(data['file'], 'String');
      }
      if (data.hasOwnProperty('file_from_content')) {
        obj['file_from_content'] = ApiClient.convertToType(data['file_from_content'], 'String');
      }
      if (data.hasOwnProperty('file_from_content_name')) {
        obj['file_from_content_name'] = ApiClient.convertToType(data['file_from_content_name'], 'String');
      }
      if (data.hasOwnProperty('file_from_url')) {
        obj['file_from_url'] = ApiClient.convertToType(data['file_from_url'], 'String');
      }
      if (data.hasOwnProperty('document')) {
        obj['document'] = ApiClient.convertToType(data['document'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {String} uuid
   */
  exports.prototype['uuid'] = undefined;
  /**
   * Defaults to filename, including extension
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Temporary URL to document attachment, expires in five minutes
   * @member {String} file
   */
  exports.prototype['file'] = undefined;
  /**
   * Base64 encoded document content
   * @member {String} file_from_content
   */
  exports.prototype['file_from_content'] = undefined;
  /**
   * Filename, including extension. Required when using `file_from_content`.
   * @member {String} file_from_content_name
   */
  exports.prototype['file_from_content_name'] = undefined;
  /**
   * Publicly accessible URL of document to be downloaded by SignRequest
   * @member {String} file_from_url
   */
  exports.prototype['file_from_url'] = undefined;
  /**
   * @member {String} document
   */
  exports.prototype['document'] = undefined;



  return exports;
}));


