/**
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SignrequestClient) {
      root.SignrequestClient = {};
    }
    root.SignrequestClient.DocumentSearch = factory(root.SignrequestClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DocumentSearch model module.
   * @module model/DocumentSearch
   * @version v1
   */

  /**
   * Constructs a new <code>DocumentSearch</code>.
   * @alias module:model/DocumentSearch
   * @class
   * @param who {String} 
   * @param nrExtraDocs {Number} 
   * @param fromEmail {String} 
   * @param autocomplete {String} 
   */
  var exports = function(who, nrExtraDocs, fromEmail, autocomplete) {
    var _this = this;



    _this['who'] = who;
    _this['nr_extra_docs'] = nrExtraDocs;
    _this['from_email'] = fromEmail;


    _this['autocomplete'] = autocomplete;







  };

  /**
   * Constructs a <code>DocumentSearch</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentSearch} obj Optional instance to populate.
   * @return {module:model/DocumentSearch} The populated <code>DocumentSearch</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('who')) {
        obj['who'] = ApiClient.convertToType(data['who'], 'String');
      }
      if (data.hasOwnProperty('nr_extra_docs')) {
        obj['nr_extra_docs'] = ApiClient.convertToType(data['nr_extra_docs'], 'Number');
      }
      if (data.hasOwnProperty('from_email')) {
        obj['from_email'] = ApiClient.convertToType(data['from_email'], 'String');
      }
      if (data.hasOwnProperty('uuid')) {
        obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
      }
      if (data.hasOwnProperty('created')) {
        obj['created'] = ApiClient.convertToType(data['created'], 'Date');
      }
      if (data.hasOwnProperty('autocomplete')) {
        obj['autocomplete'] = ApiClient.convertToType(data['autocomplete'], 'String');
      }
      if (data.hasOwnProperty('signer_emails')) {
        obj['signer_emails'] = ApiClient.convertToType(data['signer_emails'], ['String']);
      }
      if (data.hasOwnProperty('status_display')) {
        obj['status_display'] = ApiClient.convertToType(data['status_display'], 'String');
      }
      if (data.hasOwnProperty('created_timestamp')) {
        obj['created_timestamp'] = ApiClient.convertToType(data['created_timestamp'], 'Number');
      }
      if (data.hasOwnProperty('finished_on_timestamp')) {
        obj['finished_on_timestamp'] = ApiClient.convertToType(data['finished_on_timestamp'], 'Number');
      }
      if (data.hasOwnProperty('parent_doc')) {
        obj['parent_doc'] = ApiClient.convertToType(data['parent_doc'], 'String');
      }
      if (data.hasOwnProperty('finished_on')) {
        obj['finished_on'] = ApiClient.convertToType(data['finished_on'], 'Date');
      }
      if (data.hasOwnProperty('subdomain')) {
        obj['subdomain'] = ApiClient.convertToType(data['subdomain'], 'String');
      }
    }
    return obj;
  }

  /**
   * `co`: converting, `ne`: new, `se`: sent, `vi`: viewed, `si`: signed, `do`: downloaded, `sd`: signed and downloaded, `ca`: cancelled, `de`: declined, `ec`: error converting, `es`: error sending, `xp`: expired
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * Defaults to filename
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} who
   */
  exports.prototype['who'] = undefined;
  /**
   * @member {Number} nr_extra_docs
   */
  exports.prototype['nr_extra_docs'] = undefined;
  /**
   * @member {String} from_email
   */
  exports.prototype['from_email'] = undefined;
  /**
   * @member {String} uuid
   */
  exports.prototype['uuid'] = undefined;
  /**
   * @member {Date} created
   */
  exports.prototype['created'] = undefined;
  /**
   * @member {String} autocomplete
   */
  exports.prototype['autocomplete'] = undefined;
  /**
   * @member {Array.<String>} signer_emails
   */
  exports.prototype['signer_emails'] = undefined;
  /**
   * @member {String} status_display
   */
  exports.prototype['status_display'] = undefined;
  /**
   * @member {Number} created_timestamp
   */
  exports.prototype['created_timestamp'] = undefined;
  /**
   * @member {Number} finished_on_timestamp
   */
  exports.prototype['finished_on_timestamp'] = undefined;
  /**
   * @member {String} parent_doc
   */
  exports.prototype['parent_doc'] = undefined;
  /**
   * @member {Date} finished_on
   */
  exports.prototype['finished_on'] = undefined;
  /**
   * @member {String} subdomain
   */
  exports.prototype['subdomain'] = undefined;



  return exports;
}));


