/**
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SignrequestClient) {
      root.SignrequestClient = {};
    }
    root.SignrequestClient.FileFromSf = factory(root.SignrequestClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FileFromSf model module.
   * @module model/FileFromSf
   * @version v1
   */

  /**
   * Constructs a new <code>FileFromSf</code>.
   * @alias module:model/FileFromSf
   * @class
   * @param objectType {String} 
   * @param objectId {String} 
   */
  var exports = function(objectType, objectId) {
    var _this = this;

    _this['object_type'] = objectType;
    _this['object_id'] = objectId;
  };

  /**
   * Constructs a <code>FileFromSf</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FileFromSf} obj Optional instance to populate.
   * @return {module:model/FileFromSf} The populated <code>FileFromSf</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('object_type')) {
        obj['object_type'] = ApiClient.convertToType(data['object_type'], 'String');
      }
      if (data.hasOwnProperty('object_id')) {
        obj['object_id'] = ApiClient.convertToType(data['object_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} object_type
   */
  exports.prototype['object_type'] = undefined;
  /**
   * @member {String} object_id
   */
  exports.prototype['object_id'] = undefined;



  return exports;
}));


