/*
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SignrequestClient) {
      root.SignrequestClient = {};
    }
    root.SignrequestClient.InlineDocumentSignerIntegrationData = factory(root.SignrequestClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineDocumentSignerIntegrationData model module.
   * @module model/InlineDocumentSignerIntegrationData
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>InlineDocumentSignerIntegrationData</code>.
   * @alias module:model/InlineDocumentSignerIntegrationData
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>InlineDocumentSignerIntegrationData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineDocumentSignerIntegrationData} obj Optional instance to populate.
   * @return {module:model/InlineDocumentSignerIntegrationData} The populated <code>InlineDocumentSignerIntegrationData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('integration')) {
        obj['integration'] = ApiClient.convertToType(data['integration'], 'String');
      }
      if (data.hasOwnProperty('integration_data')) {
        obj['integration_data'] = ApiClient.convertToType(data['integration_data'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/InlineDocumentSignerIntegrationData.IntegrationEnum} integration
   */
  exports.prototype['integration'] = undefined;
  /**
   * @member {String} integration_data
   */
  exports.prototype['integration_data'] = undefined;


  /**
   * Allowed values for the <code>integration</code> property.
   * @enum {String}
   * @readonly
   */
  exports.IntegrationEnum = {
    /**
     * value: "mfiles"
     * @const
     */
    "mfiles": "mfiles",
    /**
     * value: "salesforce"
     * @const
     */
    "salesforce": "salesforce",
    /**
     * value: "formdesk"
     * @const
     */
    "formdesk": "formdesk",
    /**
     * value: "zapier"
     * @const
     */
    "zapier": "zapier",
    /**
     * value: "txhash"
     * @const
     */
    "txhash": "txhash"  };


  return exports;
}));


