/**
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SignrequestClient) {
      root.SignrequestClient = {};
    }
    root.SignrequestClient.Placeholder = factory(root.SignrequestClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Placeholder model module.
   * @module model/Placeholder
   * @version v1
   */

  /**
   * Constructs a new <code>Placeholder</code>.
   * @alias module:model/Placeholder
   * @class
   * @param pageIndex {Number} 
   * @param prefill {Boolean} 
   */
  var exports = function(pageIndex, prefill) {
    var _this = this;



    _this['page_index'] = pageIndex;
    _this['prefill'] = prefill;




  };

  /**
   * Constructs a <code>Placeholder</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Placeholder} obj Optional instance to populate.
   * @return {module:model/Placeholder} The populated <code>Placeholder</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('uuid')) {
        obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('page_index')) {
        obj['page_index'] = ApiClient.convertToType(data['page_index'], 'Number');
      }
      if (data.hasOwnProperty('prefill')) {
        obj['prefill'] = ApiClient.convertToType(data['prefill'], 'Boolean');
      }
      if (data.hasOwnProperty('text')) {
        obj['text'] = ApiClient.convertToType(data['text'], 'String');
      }
      if (data.hasOwnProperty('checkbox_value')) {
        obj['checkbox_value'] = ApiClient.convertToType(data['checkbox_value'], 'Boolean');
      }
      if (data.hasOwnProperty('date_value')) {
        obj['date_value'] = ApiClient.convertToType(data['date_value'], 'Date');
      }
      if (data.hasOwnProperty('external_id')) {
        obj['external_id'] = ApiClient.convertToType(data['external_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} uuid
   */
  exports.prototype['uuid'] = undefined;
  /**
   * @member {module:model/Placeholder.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Number} page_index
   */
  exports.prototype['page_index'] = undefined;
  /**
   * @member {Boolean} prefill
   */
  exports.prototype['prefill'] = undefined;
  /**
   * @member {String} text
   */
  exports.prototype['text'] = undefined;
  /**
   * @member {Boolean} checkbox_value
   */
  exports.prototype['checkbox_value'] = undefined;
  /**
   * @member {Date} date_value
   */
  exports.prototype['date_value'] = undefined;
  /**
   * @member {String} external_id
   */
  exports.prototype['external_id'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "s"
     * @const
     */
    "s": "s",
    /**
     * value: "i"
     * @const
     */
    "i": "i",
    /**
     * value: "n"
     * @const
     */
    "n": "n",
    /**
     * value: "d"
     * @const
     */
    "d": "d",
    /**
     * value: "t"
     * @const
     */
    "t": "t",
    /**
     * value: "c"
     * @const
     */
    "c": "c"  };


  return exports;
}));


