/*
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SignrequestClient) {
      root.SignrequestClient = {};
    }
    root.SignrequestClient.SignerInputs = factory(root.SignrequestClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SignerInputs model module.
   * @module model/SignerInputs
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>SignerInputs</code>.
   * @alias module:model/SignerInputs
   * @class
   * @param page_index {Number} 
   */
  var exports = function(page_index) {
    var _this = this;


    _this['page_index'] = page_index;





  };

  /**
   * Constructs a <code>SignerInputs</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SignerInputs} obj Optional instance to populate.
   * @return {module:model/SignerInputs} The populated <code>SignerInputs</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('page_index')) {
        obj['page_index'] = ApiClient.convertToType(data['page_index'], 'Number');
      }
      if (data.hasOwnProperty('text')) {
        obj['text'] = ApiClient.convertToType(data['text'], 'String');
      }
      if (data.hasOwnProperty('checkbox_value')) {
        obj['checkbox_value'] = ApiClient.convertToType(data['checkbox_value'], 'Boolean');
      }
      if (data.hasOwnProperty('date_value')) {
        obj['date_value'] = ApiClient.convertToType(data['date_value'], 'Date');
      }
      if (data.hasOwnProperty('external_id')) {
        obj['external_id'] = ApiClient.convertToType(data['external_id'], 'String');
      }
      if (data.hasOwnProperty('placeholder_uuid')) {
        obj['placeholder_uuid'] = ApiClient.convertToType(data['placeholder_uuid'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SignerInputs.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Number} page_index
   */
  exports.prototype['page_index'] = undefined;
  /**
   * @member {String} text
   */
  exports.prototype['text'] = undefined;
  /**
   * @member {Boolean} checkbox_value
   */
  exports.prototype['checkbox_value'] = undefined;
  /**
   * @member {Date} date_value
   */
  exports.prototype['date_value'] = undefined;
  /**
   * @member {String} external_id
   */
  exports.prototype['external_id'] = undefined;
  /**
   * @member {String} placeholder_uuid
   */
  exports.prototype['placeholder_uuid'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "s"
     * @const
     */
    "s": "s",
    /**
     * value: "i"
     * @const
     */
    "i": "i",
    /**
     * value: "n"
     * @const
     */
    "n": "n",
    /**
     * value: "d"
     * @const
     */
    "d": "d",
    /**
     * value: "t"
     * @const
     */
    "t": "t",
    /**
     * value: "c"
     * @const
     */
    "c": "c"  };


  return exports;
}));


