/**
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FileFromSf', 'model/InlineIntegrationData', 'model/InlinePrefillTags', 'model/RequiredAttachment', 'model/Signer'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FileFromSf'), require('./InlineIntegrationData'), require('./InlinePrefillTags'), require('./RequiredAttachment'), require('./Signer'));
  } else {
    // Browser globals (root is window)
    if (!root.SignrequestClient) {
      root.SignrequestClient = {};
    }
    root.SignrequestClient.SignRequestQuickCreate = factory(root.SignrequestClient.ApiClient, root.SignrequestClient.FileFromSf, root.SignrequestClient.InlineIntegrationData, root.SignrequestClient.InlinePrefillTags, root.SignrequestClient.RequiredAttachment, root.SignrequestClient.Signer);
  }
}(this, function(ApiClient, FileFromSf, InlineIntegrationData, InlinePrefillTags, RequiredAttachment, Signer) {
  'use strict';




  /**
   * The SignRequestQuickCreate model module.
   * @module model/SignRequestQuickCreate
   * @version v1
   */

  /**
   * Constructs a new <code>SignRequestQuickCreate</code>.
   * @alias module:model/SignRequestQuickCreate
   * @class
   * @param signers {Array.<module:model/Signer>} 
   */
  var exports = function(signers) {
    var _this = this;

















    _this['signers'] = signers;


















  };

  /**
   * Constructs a <code>SignRequestQuickCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SignRequestQuickCreate} obj Optional instance to populate.
   * @return {module:model/SignRequestQuickCreate} The populated <code>SignRequestQuickCreate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('from_email')) {
        obj['from_email'] = ApiClient.convertToType(data['from_email'], 'String');
      }
      if (data.hasOwnProperty('from_email_name')) {
        obj['from_email_name'] = ApiClient.convertToType(data['from_email_name'], 'String');
      }
      if (data.hasOwnProperty('is_being_prepared')) {
        obj['is_being_prepared'] = ApiClient.convertToType(data['is_being_prepared'], 'Boolean');
      }
      if (data.hasOwnProperty('prepare_url')) {
        obj['prepare_url'] = ApiClient.convertToType(data['prepare_url'], 'String');
      }
      if (data.hasOwnProperty('redirect_url')) {
        obj['redirect_url'] = ApiClient.convertToType(data['redirect_url'], 'String');
      }
      if (data.hasOwnProperty('required_attachments')) {
        obj['required_attachments'] = ApiClient.convertToType(data['required_attachments'], [RequiredAttachment]);
      }
      if (data.hasOwnProperty('disable_attachments')) {
        obj['disable_attachments'] = ApiClient.convertToType(data['disable_attachments'], 'Boolean');
      }
      if (data.hasOwnProperty('disable_text_signatures')) {
        obj['disable_text_signatures'] = ApiClient.convertToType(data['disable_text_signatures'], 'Boolean');
      }
      if (data.hasOwnProperty('disable_text')) {
        obj['disable_text'] = ApiClient.convertToType(data['disable_text'], 'Boolean');
      }
      if (data.hasOwnProperty('disable_date')) {
        obj['disable_date'] = ApiClient.convertToType(data['disable_date'], 'Boolean');
      }
      if (data.hasOwnProperty('disable_emails')) {
        obj['disable_emails'] = ApiClient.convertToType(data['disable_emails'], 'Boolean');
      }
      if (data.hasOwnProperty('disable_upload_signatures')) {
        obj['disable_upload_signatures'] = ApiClient.convertToType(data['disable_upload_signatures'], 'Boolean');
      }
      if (data.hasOwnProperty('subject')) {
        obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('who')) {
        obj['who'] = ApiClient.convertToType(data['who'], 'String');
      }
      if (data.hasOwnProperty('send_reminders')) {
        obj['send_reminders'] = ApiClient.convertToType(data['send_reminders'], 'Boolean');
      }
      if (data.hasOwnProperty('signers')) {
        obj['signers'] = ApiClient.convertToType(data['signers'], [Signer]);
      }
      if (data.hasOwnProperty('uuid')) {
        obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('document')) {
        obj['document'] = ApiClient.convertToType(data['document'], 'String');
      }
      if (data.hasOwnProperty('integration')) {
        obj['integration'] = ApiClient.convertToType(data['integration'], 'String');
      }
      if (data.hasOwnProperty('integration_data')) {
        obj['integration_data'] = ApiClient.convertToType(data['integration_data'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('external_id')) {
        obj['external_id'] = ApiClient.convertToType(data['external_id'], 'String');
      }
      if (data.hasOwnProperty('frontend_id')) {
        obj['frontend_id'] = ApiClient.convertToType(data['frontend_id'], 'String');
      }
      if (data.hasOwnProperty('file')) {
        obj['file'] = ApiClient.convertToType(data['file'], 'String');
      }
      if (data.hasOwnProperty('file_from_url')) {
        obj['file_from_url'] = ApiClient.convertToType(data['file_from_url'], 'String');
      }
      if (data.hasOwnProperty('events_callback_url')) {
        obj['events_callback_url'] = ApiClient.convertToType(data['events_callback_url'], 'String');
      }
      if (data.hasOwnProperty('file_from_content')) {
        obj['file_from_content'] = ApiClient.convertToType(data['file_from_content'], 'String');
      }
      if (data.hasOwnProperty('file_from_content_name')) {
        obj['file_from_content_name'] = ApiClient.convertToType(data['file_from_content_name'], 'String');
      }
      if (data.hasOwnProperty('template')) {
        obj['template'] = ApiClient.convertToType(data['template'], 'String');
      }
      if (data.hasOwnProperty('prefill_tags')) {
        obj['prefill_tags'] = ApiClient.convertToType(data['prefill_tags'], [InlinePrefillTags]);
      }
      if (data.hasOwnProperty('integrations')) {
        obj['integrations'] = ApiClient.convertToType(data['integrations'], [InlineIntegrationData]);
      }
      if (data.hasOwnProperty('file_from_sf')) {
        obj['file_from_sf'] = FileFromSf.constructFromObject(data['file_from_sf']);
      }
      if (data.hasOwnProperty('auto_delete_days')) {
        obj['auto_delete_days'] = ApiClient.convertToType(data['auto_delete_days'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Email of user sending the SignRequest (must be a validated email)
   * @member {String} from_email
   */
  exports.prototype['from_email'] = undefined;
  /**
   * Name to be used in the `From` email header, e.g. `{from_email_name} <no-reply@signrequest.com>`
   * @member {String} from_email_name
   */
  exports.prototype['from_email_name'] = undefined;
  /**
   * Have the sender of a SignRequest prepare the document before sending the request out, see: [prepare using the web interface](#section/Preparing-a-document/Prepare-using-the-web-interface)
   * @member {Boolean} is_being_prepared
   */
  exports.prototype['is_being_prepared'] = undefined;
  /**
   * @member {String} prepare_url
   */
  exports.prototype['prepare_url'] = undefined;
  /**
   * URL at which SignRequest will redirect to when a document is signed
   * @member {String} redirect_url
   */
  exports.prototype['redirect_url'] = undefined;
  /**
   * Attachments that signers are required to upload
   * @member {Array.<module:model/RequiredAttachment>} required_attachments
   */
  exports.prototype['required_attachments'] = undefined;
  /**
   * Disable uploading/adding of attachments
   * @member {Boolean} disable_attachments
   */
  exports.prototype['disable_attachments'] = undefined;
  /**
   * Disable usage of signatures generated by typing (text)
   * @member {Boolean} disable_text_signatures
   */
  exports.prototype['disable_text_signatures'] = undefined;
  /**
   * Disable adding of text
   * @member {Boolean} disable_text
   */
  exports.prototype['disable_text'] = undefined;
  /**
   * Disable adding of dates
   * @member {Boolean} disable_date
   */
  exports.prototype['disable_date'] = undefined;
  /**
   * Disable all SignRequest status emails as well as the email that contains the signed documents
   * @member {Boolean} disable_emails
   */
  exports.prototype['disable_emails'] = undefined;
  /**
   * Disable usage of uploaded signatures (images)
   * @member {Boolean} disable_upload_signatures
   */
  exports.prototype['disable_upload_signatures'] = undefined;
  /**
   * Subject of SignRequest email
   * @member {String} subject
   */
  exports.prototype['subject'] = undefined;
  /**
   * Message to include in SignRequest email, may contain the following html tags: `a`, `abbr`, `acronym`, `b`, `blockquote`, `code`, `em`, `i`, `ul`, `li`, `ol`, and `strong`
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * `m`: only me, `mo`: me and others, `o`: only others
   * @member {module:model/SignRequestQuickCreate.WhoEnum} who
   * @default 'o'
   */
  exports.prototype['who'] = 'o';
  /**
   * Automatically remind signers to sign a document
   * @member {Boolean} send_reminders
   */
  exports.prototype['send_reminders'] = undefined;
  /**
   * @member {Array.<module:model/Signer>} signers
   */
  exports.prototype['signers'] = undefined;
  /**
   * @member {String} uuid
   */
  exports.prototype['uuid'] = undefined;
  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {String} document
   */
  exports.prototype['document'] = undefined;
  /**
   * @member {module:model/SignRequestQuickCreate.IntegrationEnum} integration
   */
  exports.prototype['integration'] = undefined;
  /**
   * @member {String} integration_data
   */
  exports.prototype['integration_data'] = undefined;
  /**
   * Defaults to filename, including extension
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * ID used to reference document in external system
   * @member {String} external_id
   */
  exports.prototype['external_id'] = undefined;
  /**
   * Shared secret used in conjunction with <a href=\"#section/Frontend-API/SignRequest-js-client-(beta)\">SignRequest-js client</a> to grant user access to a document that's not a member of the document's team
   * @member {String} frontend_id
   */
  exports.prototype['frontend_id'] = undefined;
  /**
   * Temporary URL to original file, expires in five minutes
   * @member {String} file
   */
  exports.prototype['file'] = undefined;
  /**
   * Publicly accessible URL of document to be downloaded by SignRequest
   * @member {String} file_from_url
   */
  exports.prototype['file_from_url'] = undefined;
  /**
   * URL at which to receive [event callbacks](#section/Events/Events-callback) for this document
   * @member {String} events_callback_url
   */
  exports.prototype['events_callback_url'] = undefined;
  /**
   * Base64 encoded document content
   * @member {String} file_from_content
   */
  exports.prototype['file_from_content'] = undefined;
  /**
   * Filename, including extension. Required when using `file_from_content`.
   * @member {String} file_from_content_name
   */
  exports.prototype['file_from_content_name'] = undefined;
  /**
   * @member {String} template
   */
  exports.prototype['template'] = undefined;
  /**
   * Prefill signer input data, see [prefill tags](#section/Preparing-a-document/Prefill-tags-templates)
   * @member {Array.<module:model/InlinePrefillTags>} prefill_tags
   */
  exports.prototype['prefill_tags'] = undefined;
  /**
   * @member {Array.<module:model/InlineIntegrationData>} integrations
   */
  exports.prototype['integrations'] = undefined;
  /**
   * @member {module:model/FileFromSf} file_from_sf
   */
  exports.prototype['file_from_sf'] = undefined;
  /**
   * Number of days after which a finished document (signed/cancelled/declined) will be automatically deleted
   * @member {Number} auto_delete_days
   */
  exports.prototype['auto_delete_days'] = undefined;


  /**
   * Allowed values for the <code>who</code> property.
   * @enum {String}
   * @readonly
   */
  exports.WhoEnum = {
    /**
     * value: "m"
     * @const
     */
    "m": "m",
    /**
     * value: "mo"
     * @const
     */
    "mo": "mo",
    /**
     * value: "o"
     * @const
     */
    "o": "o"  };

  /**
   * Allowed values for the <code>integration</code> property.
   * @enum {String}
   * @readonly
   */
  exports.IntegrationEnum = {
    /**
     * value: "mfiles"
     * @const
     */
    "mfiles": "mfiles",
    /**
     * value: "salesforce"
     * @const
     */
    "salesforce": "salesforce",
    /**
     * value: "formdesk"
     * @const
     */
    "formdesk": "formdesk",
    /**
     * value: "zapier"
     * @const
     */
    "zapier": "zapier",
    /**
     * value: "txhash"
     * @const
     */
    "txhash": "txhash"  };


  return exports;
}));


