/*
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineTeamMember'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineTeamMember'));
  } else {
    // Browser globals (root is window)
    if (!root.SignrequestClient) {
      root.SignrequestClient = {};
    }
    root.SignrequestClient.Team = factory(root.SignrequestClient.ApiClient, root.SignrequestClient.InlineTeamMember);
  }
}(this, function(ApiClient, InlineTeamMember) {
  'use strict';




  /**
   * The Team model module.
   * @module model/Team
   * @version 1.1.1
   */

  /**
   * Constructs a new <code>Team</code>.
   * @alias module:model/Team
   * @class
   * @param name {String} 
   * @param subdomain {String} 
   */
  var exports = function(name, subdomain) {
    var _this = this;

    _this['name'] = name;
    _this['subdomain'] = subdomain;








  };

  /**
   * Constructs a <code>Team</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Team} obj Optional instance to populate.
   * @return {module:model/Team} The populated <code>Team</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('subdomain')) {
        obj['subdomain'] = ApiClient.convertToType(data['subdomain'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('logo')) {
        obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
      }
      if (data.hasOwnProperty('phone')) {
        obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
      }
      if (data.hasOwnProperty('primary_color')) {
        obj['primary_color'] = ApiClient.convertToType(data['primary_color'], 'String');
      }
      if (data.hasOwnProperty('events_callback_url')) {
        obj['events_callback_url'] = ApiClient.convertToType(data['events_callback_url'], 'String');
      }
      if (data.hasOwnProperty('members')) {
        obj['members'] = ApiClient.convertToType(data['members'], [InlineTeamMember]);
      }
      if (data.hasOwnProperty('delete_after')) {
        obj['delete_after'] = ApiClient.convertToType(data['delete_after'], 'Date');
      }
      if (data.hasOwnProperty('sandbox')) {
        obj['sandbox'] = ApiClient.convertToType(data['sandbox'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} subdomain
   */
  exports.prototype['subdomain'] = undefined;
  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {String} logo
   */
  exports.prototype['logo'] = undefined;
  /**
   * @member {String} phone
   */
  exports.prototype['phone'] = undefined;
  /**
   * @member {String} primary_color
   */
  exports.prototype['primary_color'] = undefined;
  /**
   * @member {String} events_callback_url
   */
  exports.prototype['events_callback_url'] = undefined;
  /**
   * @member {Array.<module:model/InlineTeamMember>} members
   */
  exports.prototype['members'] = undefined;
  /**
   * When filled this team will be deleted after this date
   * @member {Date} delete_after
   */
  exports.prototype['delete_after'] = undefined;
  /**
   * Indicates whether team is in Sandbox mode
   * @member {Boolean} sandbox
   */
  exports.prototype['sandbox'] = undefined;



  return exports;
}));


