/**
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SignRequestQuickCreate'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/SignRequestQuickCreate'));
  } else {
    // Browser globals (root is window)
    if (!root.SignrequestClient) {
      root.SignrequestClient = {};
    }
    root.SignrequestClient.SignrequestQuickCreateApi = factory(root.SignrequestClient.ApiClient, root.SignrequestClient.SignRequestQuickCreate);
  }
}(this, function(ApiClient, SignRequestQuickCreate) {
  'use strict';

  /**
   * SignrequestQuickCreate service.
   * @module api/SignrequestQuickCreateApi
   * @version v1
   */

  /**
   * Constructs a new SignrequestQuickCreateApi. 
   * @alias module:api/SignrequestQuickCreateApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the signrequestQuickCreateCreate operation.
     * @callback module:api/SignrequestQuickCreateApi~signrequestQuickCreateCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SignRequestQuickCreate} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Quick create a SignRequest
     * 
     * @param {module:model/SignRequestQuickCreate} data 
     * @param {module:api/SignrequestQuickCreateApi~signrequestQuickCreateCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SignRequestQuickCreate}
     */
    this.signrequestQuickCreateCreate = function(data, callback) {
      var postBody = data;

      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling signrequestQuickCreateCreate");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SignRequestQuickCreate;

      return this.apiClient.callApi(
        '/signrequest-quick-create/', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
