/**
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SignrequestClient);
  }
}(this, function(expect, SignrequestClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SignrequestClient.DocumentSearch();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DocumentSearch', function() {
    it('should create an instance of DocumentSearch', function() {
      // uncomment below and update the code to test DocumentSearch
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be.a(SignrequestClient.DocumentSearch);
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be();
    });

    it('should have the property who (base name: "who")', function() {
      // uncomment below and update the code to test the property who
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be();
    });

    it('should have the property nrExtraDocs (base name: "nr_extra_docs")', function() {
      // uncomment below and update the code to test the property nrExtraDocs
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be();
    });

    it('should have the property fromEmail (base name: "from_email")', function() {
      // uncomment below and update the code to test the property fromEmail
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be();
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be();
    });

    it('should have the property autocomplete (base name: "autocomplete")', function() {
      // uncomment below and update the code to test the property autocomplete
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be();
    });

    it('should have the property signerEmails (base name: "signer_emails")', function() {
      // uncomment below and update the code to test the property signerEmails
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be();
    });

    it('should have the property statusDisplay (base name: "status_display")', function() {
      // uncomment below and update the code to test the property statusDisplay
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be();
    });

    it('should have the property createdTimestamp (base name: "created_timestamp")', function() {
      // uncomment below and update the code to test the property createdTimestamp
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be();
    });

    it('should have the property finishedOnTimestamp (base name: "finished_on_timestamp")', function() {
      // uncomment below and update the code to test the property finishedOnTimestamp
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be();
    });

    it('should have the property parentDoc (base name: "parent_doc")', function() {
      // uncomment below and update the code to test the property parentDoc
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be();
    });

    it('should have the property finishedOn (base name: "finished_on")', function() {
      // uncomment below and update the code to test the property finishedOn
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be();
    });

    it('should have the property subdomain (base name: "subdomain")', function() {
      // uncomment below and update the code to test the property subdomain
      //var instane = new SignrequestClient.DocumentSearch();
      //expect(instance).to.be();
    });

  });

}));
