/**
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SignrequestClient);
  }
}(this, function(expect, SignrequestClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SignrequestClient.DocumentAttachment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DocumentAttachment', function() {
    it('should create an instance of DocumentAttachment', function() {
      // uncomment below and update the code to test DocumentAttachment
      //var instane = new SignrequestClient.DocumentAttachment();
      //expect(instance).to.be.a(SignrequestClient.DocumentAttachment);
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instane = new SignrequestClient.DocumentAttachment();
      //expect(instance).to.be();
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instane = new SignrequestClient.DocumentAttachment();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new SignrequestClient.DocumentAttachment();
      //expect(instance).to.be();
    });

    it('should have the property file (base name: "file")', function() {
      // uncomment below and update the code to test the property file
      //var instane = new SignrequestClient.DocumentAttachment();
      //expect(instance).to.be();
    });

    it('should have the property fileFromContent (base name: "file_from_content")', function() {
      // uncomment below and update the code to test the property fileFromContent
      //var instane = new SignrequestClient.DocumentAttachment();
      //expect(instance).to.be();
    });

    it('should have the property fileFromContentName (base name: "file_from_content_name")', function() {
      // uncomment below and update the code to test the property fileFromContentName
      //var instane = new SignrequestClient.DocumentAttachment();
      //expect(instance).to.be();
    });

    it('should have the property fileFromUrl (base name: "file_from_url")', function() {
      // uncomment below and update the code to test the property fileFromUrl
      //var instane = new SignrequestClient.DocumentAttachment();
      //expect(instance).to.be();
    });

    it('should have the property document (base name: "document")', function() {
      // uncomment below and update the code to test the property document
      //var instane = new SignrequestClient.DocumentAttachment();
      //expect(instance).to.be();
    });

  });

}));
