/*
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SignrequestClient);
  }
}(this, function(expect, SignrequestClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SignrequestClient.Document();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Document', function() {
    it('should create an instance of Document', function() {
      // uncomment below and update the code to test Document
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be.a(SignrequestClient.Document);
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property team (base name: "team")', function() {
      // uncomment below and update the code to test the property team
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property file_as_pdf (base name: "file_as_pdf")', function() {
      // uncomment below and update the code to test the property file_as_pdf
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property external_id (base name: "external_id")', function() {
      // uncomment below and update the code to test the property external_id
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property frontend_id (base name: "frontend_id")', function() {
      // uncomment below and update the code to test the property frontend_id
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property file (base name: "file")', function() {
      // uncomment below and update the code to test the property file
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property file_from_url (base name: "file_from_url")', function() {
      // uncomment below and update the code to test the property file_from_url
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property events_callback_url (base name: "events_callback_url")', function() {
      // uncomment below and update the code to test the property events_callback_url
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property file_from_content (base name: "file_from_content")', function() {
      // uncomment below and update the code to test the property file_from_content
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property file_from_content_name (base name: "file_from_content_name")', function() {
      // uncomment below and update the code to test the property file_from_content_name
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property template (base name: "template")', function() {
      // uncomment below and update the code to test the property template
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property prefill_tags (base name: "prefill_tags")', function() {
      // uncomment below and update the code to test the property prefill_tags
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property integrations (base name: "integrations")', function() {
      // uncomment below and update the code to test the property integrations
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property file_from_sf (base name: "file_from_sf")', function() {
      // uncomment below and update the code to test the property file_from_sf
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property auto_delete_days (base name: "auto_delete_days")', function() {
      // uncomment below and update the code to test the property auto_delete_days
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property auto_expire_days (base name: "auto_expire_days")', function() {
      // uncomment below and update the code to test the property auto_expire_days
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property pdf (base name: "pdf")', function() {
      // uncomment below and update the code to test the property pdf
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property signrequest (base name: "signrequest")', function() {
      // uncomment below and update the code to test the property signrequest
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property api_used (base name: "api_used")', function() {
      // uncomment below and update the code to test the property api_used
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property signing_log (base name: "signing_log")', function() {
      // uncomment below and update the code to test the property signing_log
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property security_hash (base name: "security_hash")', function() {
      // uncomment below and update the code to test the property security_hash
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property attachments (base name: "attachments")', function() {
      // uncomment below and update the code to test the property attachments
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property auto_delete_after (base name: "auto_delete_after")', function() {
      // uncomment below and update the code to test the property auto_delete_after
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property sandbox (base name: "sandbox")', function() {
      // uncomment below and update the code to test the property sandbox
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

    it('should have the property auto_expire_after (base name: "auto_expire_after")', function() {
      // uncomment below and update the code to test the property auto_expire_after
      //var instance = new SignrequestClient.Document();
      //expect(instance).to.be();
    });

  });

}));
