/*
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SignrequestClient);
  }
}(this, function(expect, SignrequestClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SignrequestClient.SignRequestQuickCreate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SignRequestQuickCreate', function() {
    it('should create an instance of SignRequestQuickCreate', function() {
      // uncomment below and update the code to test SignRequestQuickCreate
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be.a(SignrequestClient.SignRequestQuickCreate);
    });

    it('should have the property from_email (base name: "from_email")', function() {
      // uncomment below and update the code to test the property from_email
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property from_email_name (base name: "from_email_name")', function() {
      // uncomment below and update the code to test the property from_email_name
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property is_being_prepared (base name: "is_being_prepared")', function() {
      // uncomment below and update the code to test the property is_being_prepared
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property prepare_url (base name: "prepare_url")', function() {
      // uncomment below and update the code to test the property prepare_url
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property redirect_url (base name: "redirect_url")', function() {
      // uncomment below and update the code to test the property redirect_url
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property redirect_url_declined (base name: "redirect_url_declined")', function() {
      // uncomment below and update the code to test the property redirect_url_declined
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property required_attachments (base name: "required_attachments")', function() {
      // uncomment below and update the code to test the property required_attachments
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property disable_attachments (base name: "disable_attachments")', function() {
      // uncomment below and update the code to test the property disable_attachments
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property disable_text_signatures (base name: "disable_text_signatures")', function() {
      // uncomment below and update the code to test the property disable_text_signatures
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property disable_text (base name: "disable_text")', function() {
      // uncomment below and update the code to test the property disable_text
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property disable_date (base name: "disable_date")', function() {
      // uncomment below and update the code to test the property disable_date
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property disable_emails (base name: "disable_emails")', function() {
      // uncomment below and update the code to test the property disable_emails
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property disable_upload_signatures (base name: "disable_upload_signatures")', function() {
      // uncomment below and update the code to test the property disable_upload_signatures
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property disable_blockchain_proof (base name: "disable_blockchain_proof")', function() {
      // uncomment below and update the code to test the property disable_blockchain_proof
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property text_message_verification_locked (base name: "text_message_verification_locked")', function() {
      // uncomment below and update the code to test the property text_message_verification_locked
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property who (base name: "who")', function() {
      // uncomment below and update the code to test the property who
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property send_reminders (base name: "send_reminders")', function() {
      // uncomment below and update the code to test the property send_reminders
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property signers (base name: "signers")', function() {
      // uncomment below and update the code to test the property signers
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property document (base name: "document")', function() {
      // uncomment below and update the code to test the property document
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property integration (base name: "integration")', function() {
      // uncomment below and update the code to test the property integration
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property integration_data (base name: "integration_data")', function() {
      // uncomment below and update the code to test the property integration_data
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property external_id (base name: "external_id")', function() {
      // uncomment below and update the code to test the property external_id
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property frontend_id (base name: "frontend_id")', function() {
      // uncomment below and update the code to test the property frontend_id
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property file (base name: "file")', function() {
      // uncomment below and update the code to test the property file
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property file_from_url (base name: "file_from_url")', function() {
      // uncomment below and update the code to test the property file_from_url
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property events_callback_url (base name: "events_callback_url")', function() {
      // uncomment below and update the code to test the property events_callback_url
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property file_from_content (base name: "file_from_content")', function() {
      // uncomment below and update the code to test the property file_from_content
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property file_from_content_name (base name: "file_from_content_name")', function() {
      // uncomment below and update the code to test the property file_from_content_name
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property template (base name: "template")', function() {
      // uncomment below and update the code to test the property template
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property prefill_tags (base name: "prefill_tags")', function() {
      // uncomment below and update the code to test the property prefill_tags
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property integrations (base name: "integrations")', function() {
      // uncomment below and update the code to test the property integrations
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property file_from_sf (base name: "file_from_sf")', function() {
      // uncomment below and update the code to test the property file_from_sf
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property auto_delete_days (base name: "auto_delete_days")', function() {
      // uncomment below and update the code to test the property auto_delete_days
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property auto_expire_days (base name: "auto_expire_days")', function() {
      // uncomment below and update the code to test the property auto_expire_days
      //var instance = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

  });

}));
