/**
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SignrequestClient);
  }
}(this, function(expect, SignrequestClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SignrequestClient.SignRequestQuickCreate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SignRequestQuickCreate', function() {
    it('should create an instance of SignRequestQuickCreate', function() {
      // uncomment below and update the code to test SignRequestQuickCreate
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be.a(SignrequestClient.SignRequestQuickCreate);
    });

    it('should have the property fromEmail (base name: "from_email")', function() {
      // uncomment below and update the code to test the property fromEmail
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property fromEmailName (base name: "from_email_name")', function() {
      // uncomment below and update the code to test the property fromEmailName
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property isBeingPrepared (base name: "is_being_prepared")', function() {
      // uncomment below and update the code to test the property isBeingPrepared
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property prepareUrl (base name: "prepare_url")', function() {
      // uncomment below and update the code to test the property prepareUrl
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property redirectUrl (base name: "redirect_url")', function() {
      // uncomment below and update the code to test the property redirectUrl
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property requiredAttachments (base name: "required_attachments")', function() {
      // uncomment below and update the code to test the property requiredAttachments
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property disableAttachments (base name: "disable_attachments")', function() {
      // uncomment below and update the code to test the property disableAttachments
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property disableTextSignatures (base name: "disable_text_signatures")', function() {
      // uncomment below and update the code to test the property disableTextSignatures
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property disableText (base name: "disable_text")', function() {
      // uncomment below and update the code to test the property disableText
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property disableDate (base name: "disable_date")', function() {
      // uncomment below and update the code to test the property disableDate
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property disableEmails (base name: "disable_emails")', function() {
      // uncomment below and update the code to test the property disableEmails
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property disableUploadSignatures (base name: "disable_upload_signatures")', function() {
      // uncomment below and update the code to test the property disableUploadSignatures
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property who (base name: "who")', function() {
      // uncomment below and update the code to test the property who
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property sendReminders (base name: "send_reminders")', function() {
      // uncomment below and update the code to test the property sendReminders
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property signers (base name: "signers")', function() {
      // uncomment below and update the code to test the property signers
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property document (base name: "document")', function() {
      // uncomment below and update the code to test the property document
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property integration (base name: "integration")', function() {
      // uncomment below and update the code to test the property integration
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property integrationData (base name: "integration_data")', function() {
      // uncomment below and update the code to test the property integrationData
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property externalId (base name: "external_id")', function() {
      // uncomment below and update the code to test the property externalId
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property frontendId (base name: "frontend_id")', function() {
      // uncomment below and update the code to test the property frontendId
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property file (base name: "file")', function() {
      // uncomment below and update the code to test the property file
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property fileFromUrl (base name: "file_from_url")', function() {
      // uncomment below and update the code to test the property fileFromUrl
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property eventsCallbackUrl (base name: "events_callback_url")', function() {
      // uncomment below and update the code to test the property eventsCallbackUrl
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property fileFromContent (base name: "file_from_content")', function() {
      // uncomment below and update the code to test the property fileFromContent
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property fileFromContentName (base name: "file_from_content_name")', function() {
      // uncomment below and update the code to test the property fileFromContentName
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property template (base name: "template")', function() {
      // uncomment below and update the code to test the property template
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property prefillTags (base name: "prefill_tags")', function() {
      // uncomment below and update the code to test the property prefillTags
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property integrations (base name: "integrations")', function() {
      // uncomment below and update the code to test the property integrations
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property fileFromSf (base name: "file_from_sf")', function() {
      // uncomment below and update the code to test the property fileFromSf
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

    it('should have the property autoDeleteDays (base name: "auto_delete_days")', function() {
      // uncomment below and update the code to test the property autoDeleteDays
      //var instane = new SignrequestClient.SignRequestQuickCreate();
      //expect(instance).to.be();
    });

  });

}));
