/*
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SignrequestClient);
  }
}(this, function(expect, SignrequestClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SignrequestClient.TeamMember();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TeamMember', function() {
    it('should create an instance of TeamMember', function() {
      // uncomment below and update the code to test TeamMember
      //var instance = new SignrequestClient.TeamMember();
      //expect(instance).to.be.a(SignrequestClient.TeamMember);
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instance = new SignrequestClient.TeamMember();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new SignrequestClient.TeamMember();
      //expect(instance).to.be();
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instance = new SignrequestClient.TeamMember();
      //expect(instance).to.be();
    });

    it('should have the property team (base name: "team")', function() {
      // uncomment below and update the code to test the property team
      //var instance = new SignrequestClient.TeamMember();
      //expect(instance).to.be();
    });

    it('should have the property is_admin (base name: "is_admin")', function() {
      // uncomment below and update the code to test the property is_admin
      //var instance = new SignrequestClient.TeamMember();
      //expect(instance).to.be();
    });

    it('should have the property is_active (base name: "is_active")', function() {
      // uncomment below and update the code to test the property is_active
      //var instance = new SignrequestClient.TeamMember();
      //expect(instance).to.be();
    });

    it('should have the property is_owner (base name: "is_owner")', function() {
      // uncomment below and update the code to test the property is_owner
      //var instance = new SignrequestClient.TeamMember();
      //expect(instance).to.be();
    });

  });

}));
