/*
 * SignRequest API
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SignrequestClient);
  }
}(this, function(expect, SignrequestClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SignrequestClient.SignrequestsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SignrequestsApi', function() {
    describe('signrequestsCancelSignrequest', function() {
      it('should call signrequestsCancelSignrequest successfully', function(done) {
        //uncomment below and update the code to test signrequestsCancelSignrequest
        //instance.signrequestsCancelSignrequest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('signrequestsCreate', function() {
      it('should call signrequestsCreate successfully', function(done) {
        //uncomment below and update the code to test signrequestsCreate
        //instance.signrequestsCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('signrequestsList', function() {
      it('should call signrequestsList successfully', function(done) {
        //uncomment below and update the code to test signrequestsList
        //instance.signrequestsList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('signrequestsRead', function() {
      it('should call signrequestsRead successfully', function(done) {
        //uncomment below and update the code to test signrequestsRead
        //instance.signrequestsRead(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('signrequestsResendSignrequestEmail', function() {
      it('should call signrequestsResendSignrequestEmail successfully', function(done) {
        //uncomment below and update the code to test signrequestsResendSignrequestEmail
        //instance.signrequestsResendSignrequestEmail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
